### ISSUE TITLE
Fixes, Improvements, and Upgrades

### ISSUE THREAD

**Issue by jerodg** [FuturePathAI/Learn-AI-Engineering#13]
Wow. I wasn’t expecting so much feedback. Instead of simply recognizing the faults I have decided to contribute instead. I have a pull request ready that does some cleanup/fixes/improvements/modernization to the project that alleviates some of the issues I mentioned.

Can I get access to the git repo so that I can push a new branch and create the pull request for review?

**Comment by NirantK** [comment]
Please fork and raise a PR? Don't need repo access for that?

**Comment by NirantK** [comment]
Closing the issue due to inactivity
