### ISSUE TITLE
Consolidate Notebooks 1-4 into a Single Comprehensive Notebook

### ISSUE THREAD

**Issue by NirantK** [FuturePathAI/Learn-AI-Engineering#14]
1. Merge Notebooks 1-4 into a single, cohesive notebook
2. Ensure the new notebook is self-contained
3. Maintain logical flow — add section headers and flow diagrams where relevant

**Comment by RheagalFire** [comment]
How are we following the prefixes(i.e. in context of notebook names) in these notebooks? Do we want these to be present in the notebook?

**Comment by NirantK** [comment]
> How are we following the prefixes(i.e. in context of notebook names) in these notebooks? Do we want these to be present in the notebook?

We need something to sort them — chapter01 is just one way to do this. Any ordering prefix works as long as it's consistent across notebooks.
