### ISSUE TITLE
[TODO] Add a DSPy Notebook

### ISSUE THREAD

**Issue by NirantK** [FuturePathAI/Learn-AI-Engineering#20]
1. Outline and develop a new lecture focused on DSPy
2. Add this after the Text Classification Assignment
3. Add this after the Prompt Examples, before orchestration

**Comment by NirantK** [comment]
1. Base it on this [notebook](https://github.com/weaviate/recipes/blob/main/integrations/dspy/1.Getting-Started-with-RAG-in-DSPy.ipynb)
2. Use Qdrant
3. Use the corpora from RAG Challenge of Cohort 1

**Comment by RheagalFire** [comment]
@Nirant Is this to be demonstrated as a solution to the assignment. If not then can restructure according to this ? 
- Intro 
- Concept Overview (Signatures , Teleprompters)
- Custom RM Pipeline (Qdrant with choice of using any embeddings) 
- Metric Definition 
- Score on Uncompiled Pipeline 
- Optimisers (Bootstrap and Bayesian) 
- Score on Compiled Pipeline

**Comment by NirantK** [comment]
@RheagalFire restructure as an introduction to DSPy. Borrow from their docs and case studies to the maximum extent possible. 

Areas I'm particularly interested in: 
1. Optimizer: Specially MIRO
2. Code Walkthrough: Using DSPy for simple RAG with Bootstrap Sampling. This'd overlap with your recommendations!

Notebook filename: Week2-Lecture1-DSPy101.ipynb
